import { TSkupiny } from "../models/SkupinyModel";

export const skupiny: TSkupiny[] = [
    {
        nazev: "AM",
        zakladniskupina: true,
        popis: "Malý motocykl nebo moped (do 45 km/hod.)",
        vlastneneSkupiny: [],
        podrazeneSkupiny: [],
        nadrazeneSkupiny: ["A1", "A2", "A"],
        rozsireniNaSkupiny: ["A1", "A2", "A"],
    },

    {
        nazev: "A1",
        zakladniskupina: true,
        popis: "Motocykl do objemu 125 ccm a do výkonu 11 kW",
        vlastneneSkupiny: [],
        podrazeneSkupiny: ["AM"],
        nadrazeneSkupiny: ["A2", "A"],
        rozsireniNaSkupiny: ["A2", "A"],
    },

    {
        nazev: "A2",
        zakladniskupina: true,
        popis: "Motocykl do výkonu 35 kW",
        vlastneneSkupiny: [],
        podrazeneSkupiny: ["AM", "A1"],
        nadrazeneSkupiny: ["A"],
        rozsireniNaSkupiny: ["A"],
    },

    {
        nazev: "A",
        zakladniskupina: true,
        popis: "Motocykl bez omezení výkonu",
        vlastneneSkupiny: [],
        podrazeneSkupiny: ["AM", "A1", "A2"],
        nadrazeneSkupiny: [],
        rozsireniNaSkupiny: [],
    },

    {
        nazev: "B1",
        zakladniskupina: true,
        popis: "Tříkolová a čtyřkolová malá vozidla",
        vlastneneSkupiny: [],
        podrazeneSkupiny: [],
        nadrazeneSkupiny: [],
        rozsireniNaSkupiny: [],
    },
    {
        nazev: "B",
        zakladniskupina: true,
        popis: "Osobní automobil",
        vlastneneSkupiny: [],
        podrazeneSkupiny: ["B1"],
        nadrazeneSkupiny: [
            "B96",
            "B+E",
            "C1",
            "C1+E",
            "C",
            "C+E",
            "D",
            "D+E",
            "D1",
            "D1+E",
        ],
        rozsireniNaSkupiny: ["B96", "B+E", "C", "D"],
    },
    {
        nazev: "B96",
        zakladniskupina: false,
        popis: "Os. automobil s přívěsem (souprava do 4250 kg)",
        vlastneneSkupiny: ["B"],
        podrazeneSkupiny: ["B"],
        nadrazeneSkupiny: ["B+E"],
        rozsireniNaSkupiny: ["B+E"],
    },
    {
        nazev: "B+E",
        zakladniskupina: false,
        vlastneneSkupiny: ["B", "B96"],
        popis: "Osobní automobil s přívěsem",
        podrazeneSkupiny: ["B1", "B", "B96"],
        nadrazeneSkupiny: [],
        rozsireniNaSkupiny: [],
    },
    {
        nazev: "C1",
        zakladniskupina: false,
        popis: "Nákladní automobil od 3500 kg do 7500 kg",
        vlastneneSkupiny: ["B", "D"],
        podrazeneSkupiny: ["B", "B1"],
        nadrazeneSkupiny: ["C1+E", "C+E", "C"],
        rozsireniNaSkupiny: ["C1+E", "C"],
    },
    {
        nazev: "C1+E",
        zakladniskupina: false,
        popis: "C1 s přívěsem nad 750 kg",
        vlastneneSkupiny: ["C1"],
        podrazeneSkupiny: ["B", "C1"],
        nadrazeneSkupiny: ["C+E"],
        rozsireniNaSkupiny: [],
    },
    {
        nazev: "C",
        zakladniskupina: false,
        popis: "Nákladní automobil",
        vlastneneSkupiny: ["B", "D"],
        podrazeneSkupiny: ["B1", "B", "C1"],
        nadrazeneSkupiny: ["C+E"],
        rozsireniNaSkupiny: ["C+E", "D"],
    },

    {
        nazev: "C+E",
        zakladniskupina: false,
        popis: "Nákladní automobil s přívěsem",
        vlastneneSkupiny: ["C"],
        podrazeneSkupiny: ["B", "C", "C1", "B96", "B+E", "C1+E"],
        nadrazeneSkupiny: [],
        rozsireniNaSkupiny: [],
    },
    {
        nazev: "D1",
        zakladniskupina: false,
        popis: "Autobus do 15 míst",
        vlastneneSkupiny: ["B", "C"],
        podrazeneSkupiny: ["B"],
        nadrazeneSkupiny: ["D1+E", "D", "D+E"],
        rozsireniNaSkupiny: ["D1+E", "D"],
    },
    {
        nazev: "D1+E",
        zakladniskupina: false,
        popis: "Malý autobus do 16 + 1 míst k sezení s přívěsem",
        vlastneneSkupiny: ["D1"],
        podrazeneSkupiny: ["D1", "B", "B96", "B+E"],
        nadrazeneSkupiny: ["D+E"],
        rozsireniNaSkupiny: [],
    },
    {
        nazev: "D",
        zakladniskupina: false,
        popis: "Autobus",
        vlastneneSkupiny: ["B", "C", "C1"],
        podrazeneSkupiny: ["B1", "B", "D1"],
        nadrazeneSkupiny: ["D+E"],
        rozsireniNaSkupiny: ["D+E"],
    },
    {
        nazev: "D+E",
        zakladniskupina: false,
        popis: "Autobus s přívěsem",
        vlastneneSkupiny: ["D"],
        podrazeneSkupiny: ["B", "B1", "D", "D1", "D1+E", "B+E", "B96"],
        nadrazeneSkupiny: [],
        rozsireniNaSkupiny: [],
    },
    {
        nazev: "T",
        zakladniskupina: true,
        popis: "Traktor",
        vlastneneSkupiny: [],
        podrazeneSkupiny: [],
        nadrazeneSkupiny: [],
        rozsireniNaSkupiny: [],
    },
];

export default skupiny;
